name: Publish Docker Image
on:
  push:
    branches: [ master ]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    steps:
    - name: Check out the repo
      uses: actions/checkout@v2
    - name: Push to Github Packages
      uses: docker/build-push-action@v2.4.0
      with:
        username: ${{ github.actor }}
        password: ${{ secrets.GITGUB_PAT }}
        registry: ghcr.io
        repository: taosx/migrate
        tags: ${{ github.sha }}
        dockerfile: Dockerfile
